### ISSUE TITLE
Error when clicking buttons

### ISSUE THREAD

**Issue by MartinLottering** [officialdoniald/Xamarin.Forms.Save.Open.PDF#2]
Hi, on both buttons, I get this error:
Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference'

Isn't the applicationmanifest supposed to specify FileProvider details?

**Comment by QXLTD** [comment]
Dif you find any solution for this ?
i am also facing issue in Andoird while tying to open file 

-------------------------------
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
-------------------------------------------------------

  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <9324da45a6654f83baffa7c2854d836a>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <9324da45a6654f83baffa7c2854d836a>:0 
  at Android.Support.V4.Content.FileProvider.GetUriForFile (Android.Content.Context context, System.String authority, Java.IO.File file) [0x00070] in <fb0c55a748614587b658fc2ca38fdfc2>:0 
  at Droid.Implementations.PDFSaveAndOpen.SaveAndView (System.String fileName, System.String contentType, System.IO.MemoryStream stream, Xamarin.Forms.Save.Open.PDF.PDFOpenContext context) [0x001ba] in /Users/usr/Downloads/Xamarin.Forms.Save.Open.PDF-master/Xamarin.Forms.Save.Open.PDF/Xamarin.Forms.Save.Open.PDF.Android/PDFSaveAndOpen.cs:64 
  at Xamarin.Forms.Save.Open.PDF.MainPage.Button_Clicked (System.Object sender, System.EventArgs e) [0x00054] in /Users/usr/Downloads/Xamarin.Forms.Save.Open.PDF-master/Xamarin.Forms.Save.Open.PDF/Xamarin.Forms.Save.Open.PDF/MainPage.xaml.cs:22 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <8f08acfe539e4f929df18f5cdb660998>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <8f08acfe539e4f929df18f5cdb660998>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <8f08acfe539e4f929df18f5cdb660998>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.32(intptr,intptr)
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:591)
	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:565)
	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:403)
	at crc64720bb2db43a66fe9.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
	at crc64720bb2db43a66fe9.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by QXLTD** [comment]
to resolve this issue make sure you have the same authority set in code-behind and manifest file
  instead of **provider** it should be a **file provider** resolve issue

- Android.Net.Uri path = FileProvider.GetUriForFile(Forms.Context, **Android.App.Application.Context.PackageName + ".fileprovider"**, file);

and
 
- <provider android:name="android.support.v4.content.FileProvider" android:authorities=**"${applicationId}.fileprovider"** android:exported="false" android:grantUriPermissions="true">
